
  Preparing the environment for use of 2020 stage.

The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) Stages/2020
Setting HOROVOD_MPI_THREADS_DISABLE=1. 
cpu_bind=NONE - jrc0388, task  3  3 [29488]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0388, task  0  0 [29489]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0388, task  1  1 [29490]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0388, task  2  2 [29491]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "../../main.py", line 1001, in <module>
    model, lossar, time_elapsed = train_model(smodel, optimizer)
  File "../../main.py", line 775, in train_model
    lossout('Average_loss_', 'Epoch', lossar, epoch,
  File "/p/project/delia-mp/cherepashkin1/circles_public/helpers.py", line 210, in lossout
    lossfig(jn(dirname, fnm), lossar,
  File "/p/project/delia-mp/cherepashkin1/circles_public/helpers.py", line 175, in lossfig
    plt.plot(
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 2824, in plot
    return gca().plot(
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 2352, in gca
    return gcf().gca(**kwargs)
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 731, in gcf
    return figure()
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 671, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/pyplot.py", line 299, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/p/software/jurecadc/stages/2020/software/SciPy-Stack/2021-gcccoremkl-10.3.0-2021.2.0-Python-3.8.5/lib/python3.8/site-packages/matplotlib-3.3.1-py3.8-linux-x86_64.egg/matplotlib/backends/_backend_tk.py", line 868, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-10.3.0/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:16.0"
srun: error: jrc0388: task 0: Exited with exit code 1
srun: error: jrc0388: tasks 1-3: Terminated
srun: Force Terminated job step 10188234.0
