
  Preparing the environment for use of 2020 stage.

The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) Stages/2020
Setting HOROVOD_MPI_THREADS_DISABLE=1. 
cpu_bind=NONE - jrc0193, task  2  2 [32114]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [32115]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [32116]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [32117]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 2-3: Exited with exit code 1
srun: error: jrc0193: task 1: Terminated
srun: Force Terminated job step 10175326.0
cpu_bind=NONE - jrc0193, task  2  2 [3524]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [3522]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [3523]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [3525]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  1  1 [5896]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [5897]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [5899]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [5898]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  0  0 [8237]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [8234]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [8235]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [8236]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  3  3 [10821]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [10820]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [10822]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [10823]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  1  1 [13050]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [13052]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [13051]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [13053]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  1  1 [15271]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [15272]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [15269]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [15270]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  3  3 [17475]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [17476]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [17474]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [17477]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  2  2 [19767]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [19768]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  3  3 [19766]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [19765]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
cpu_bind=NONE - jrc0193, task  3  3 [22139]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  1  1 [22140]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  0  0 [22138]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
cpu_bind=NONE - jrc0193, task  2  2 [22141]: mask 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff set
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 674, in _broadcast_async
    handle = getattr(mpi_lib, function)(
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../main.py", line 987, in <module>
    hvd.broadcast_parameters(smodel.state_dict(), root_rank=0)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/functions.py", line 54, in broadcast_parameters
    handle = broadcast_async_(p, root_rank, name)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 775, in broadcast_async_
    return _broadcast_async(tensor, tensor, root_rank, name, process_set)
  File "/p/software/jurecadc/stages/2020/software/Horovod/0.23.0-gomkl-2021-Python-3.8.5/lib/python3.8/site-packages/horovod/torch/mpi_ops.py", line 678, in _broadcast_async
    raise HorovodInternalError(e)
horovod.common.exceptions.HorovodInternalError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
srun: error: jrc0193: tasks 1-3: Exited with exit code 1
